name: flutter_pokedex
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc_concurrency: ^0.2.0
  equatable: ^2.0.3
  flutter_bloc: ^8.1.1
  http: ^0.13.0
  pokemon_repository:
    path: packages/pokemon_repository
  sqflite: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  bloc_test: ^9.0.0
  very_good_analysis: ^3.0.1

flutter:

  uses-material-design: true

