name: pokemon_repository
description: A Dart Repository which manages the pokemon domain
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  equatable: ^2.0.3
  poke_api:
    path: ../poke_api
  favourite_pokemon_table:
    path: ../favourite_pokemon_table

dev_dependencies:
  very_good_analysis: ^3.0.2