name: weather_bloc
description: A Flutter app displaying weather implementing BLOC

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  google_fonts: ^3.0.1
  hydrated_bloc: ^9.0.0
  json_annotation: ^4.4.0
  path_provider: ^2.0.8
  weather_repository:
    path: packages/weather_repository

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  bloc_test: ^9.1.0
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.2

flutter:

  uses-material-design: true
